/*
 *
 * AddressPage constants
 *
 */

export const CHANGE_N_KEY = 'app/AddressPage/CHANGE_N_KEY';
export const CHANGE_M_KEY = 'app/AddressPage/CHANGE_M_KEY';

export const GENERATE_SINGLE_SIG_ADDRESS = 'app/AddressPage/GENERATE_SINGLE_SIG_ADDRESS';
export const GENERATE_SINGLE_SIG_ADDRESS_SUCCESS = 'app/AddressPage/GENERATE_SINGLE_SIG_ADDRESS_SUCCESS';
export const GENERATE_SINGLE_SIG_ADDRESS_ERROR = 'app/AddressPage/GENERATE_SINGLE_SIG_ADDRESS_ERROR';

export const GENERATE_SINGLE_SIG_ADDRESS_CUSTOM = 'app/AddressPage/GENERATE_SINGLE_SIG_ADDRESS_CUSTOM';
export const GENERATE_SINGLE_SIG_ADDRESS_CUSTOM_SUCCESS = 'app/AddressPage/GENERATE_SINGLE_SIG_ADDRESS_CUSTOM_SUCCESS';
export const GENERATE_SINGLE_SIG_ADDRESS_CUSTOM_ERROR = 'app/AddressPage/GENERATE_SINGLE_SIG_ADDRESS_CUSTOM_ERROR';

export const CHANGE_SEED_SINGLE_CUSTOM = 'app/AddressPage/CHANGE_SEED_SINGLE_CUSTOM';
export const CHANGE_SEED_SINGLE_NONCE = 'app/AddressPage/CHANGE_SEED_SINGLE_NONCE';

export const GENERATE_MULTI_SIG_ADDRESS = 'app/AddressPage/GENERATE_MULTI_SIG_ADDRESS';
export const GENERATE_MULTI_SIG_ADDRESS_SUCCESS = 'app/AddressPage/GENERATE_MULTI_SIG_ADDRESS_SUCCESS';
export const GENERATE_MULTI_SIG_ADDRESS_ERROR = 'app/AddressPage/GENERATE_MULTI_SIG_ADDRESS_ERROR';

export const CHANGE_CUSTOM_PUB_KEY_STATUS = 'app/AddressPage/CHANGE_CUSTOM_PUB_KEY_STATUS';
export const CHANGE_PUB_KEY_VALUE = 'app/AddressPage/CHANGE_PUB_KEY_VALUE';
